#!/bin/bash 
# This script checks the existence of a file 
echo "Checking..." 
if ! [[ "$#" -eq 1 ]]; then
	echo "must have 1 arg";
	exit 1;
fi
if [[ -f $1 ]] 
then 
 echo "$1 existe." 
else 
 echo "$1 não existe" 
fi 
echo "...done."
