#!/bin/bash 
#This script does a very simple test for checking disk space. 
space=$(df -h | awk '{print $5}' | grep % | grep -v Use | sort -n | tail -1 | cut -d "%" -f1 -) 
direc=$(df -h | grep $space% | awk '{print $1}')
echo "largest occupied space = $space%" 

if [[ $space -lt 70 ]]; then
   Message="All OK."
elif [[ $space -lt 90 ]]; then
   Message="Cleaning out. One partition is $space % full." 
elif [[ $space -lt 99 ]]; then
   Message="Better buy a new disk.  One partition is $space % full." 
elif [[ $space -eq 99 ]]; then
   Message="I'm drowning here!  There's a partition at $space %!"
else
   Message="I seem to be running with a non-existent disk..."
fi
echo $Message
echo "The biggest directory was $direc"
