#!/bin/bash 
# For all the files in a folder, show their properties 
if [[ "$#" -gt 2 ]] || [[ "$#" -lt 1 ]]; then
    echo "must provide exactly 1 or 2 args"
    exit 1;
fi
if ! [[ -d "$1" ]] && ! [[ -d "$2" ]]; then
    echo "must be a directory"
    exit 1;
fi

if [[ "$1" == "-r" ]];then
for f in "$2"/* 
do 
    base=${f##*new_}
    target="$2/$base"
    mv "$f" "$target"

done
exit 1;
fi

for f in "$1"/* 
do 
    base=${f##*/}
    target="$1/new_$base"
    mv "$f" "$target"
done
